import { DomainPreset } from '../types';

export const DOMAIN_PRESETS: DomainPreset[] = [
  {
    id: 'viscoelasticity',
    name: 'Viscoelastic Stress Relaxation',
    category: 'Rheology & Polymers',
    description: 'Models time-dependent stress buildup and strain energy dissipation with exponential memory fading.',
    unitLambda: 'MPa·s (Viscous Dissipation)',
    unitPotential: 'MJ/m³ (Strain Energy)',
    defaultParams: {
      Kc: 1.25,
      timeSpan: 10,
      kernelType: 'exponential',
      kernelParams: { beta: 0.4, alpha: 1, sigma: 1, mu: 5, windowWidth: 3, frequency: 1 },
      potentialType: 'exponential_decay',
      potentialParams: { U0: 100, U_inf: 10, k: 0.8, shockTime: 2, shockSteepness: 5, frequency: 2, damping: 0.5 },
    },
    interpretation: {
      U: 'Elastic Strain Energy Density U(t)',
      minus_dU_dt: 'Rate of Mechanical Energy Release (-dU/dt)',
      Phi: 'Viscoelastic Relaxation Memory Kernel Φ(t)',
      Lambda: 'Total Accumulated Viscous Dissipation Λ',
      Kc: 'Material Modulus / Coupling Coefficient Kc',
    },
  },
  {
    id: 'material_fatigue',
    name: 'Cyclic Structural Fatigue & Damage',
    category: 'Fracture Mechanics',
    description: 'Evaluates micro-crack damage accumulation under cyclic strain drops with power-law memory decay.',
    unitLambda: 'D ∈ [0, 1] (Damage Index)',
    unitPotential: 'kJ (Stored Elastic Energy)',
    defaultParams: {
      Kc: 0.005,
      timeSpan: 15,
      kernelType: 'power_law',
      kernelParams: { beta: 0.3, alpha: 0.8, sigma: 1, mu: 5, windowWidth: 3, frequency: 1 },
      potentialType: 'cyclic_damping',
      potentialParams: { U0: 80, U_inf: 5, k: 0.2, shockTime: 3, shockSteepness: 4, frequency: 2.5, damping: 0.15 },
    },
    interpretation: {
      U: 'Structural Strain Potential U(t)',
      minus_dU_dt: 'Cyclic Strain Energy Release Rate (-dU/dt)',
      Phi: 'Fatigue Memory / Micro-damage Kernel Φ(t)',
      Lambda: 'Cumulative Crack Damage Parameter Λ',
      Kc: 'Stress Intensity Scaling Factor Kc',
    },
  },
  {
    id: 'thermal_dissipation',
    name: 'Thermodynamic Heat Dissipation',
    category: 'Thermodynamics',
    description: 'Tracks entropy generation and heat flux when thermal potential drops across a non-isothermal boundary.',
    unitLambda: 'kJ / K (Entropy Production)',
    unitPotential: 'kJ (Thermal Free Energy)',
    defaultParams: {
      Kc: 1.0,
      timeSpan: 12,
      kernelType: 'gaussian',
      kernelParams: { beta: 0.5, alpha: 1, sigma: 2.0, mu: 4.0, windowWidth: 3, frequency: 1 },
      potentialType: 'step_release',
      potentialParams: { U0: 150, U_inf: 20, k: 0.5, shockTime: 4.0, shockSteepness: 3.0, frequency: 1, damping: 0.2 },
    },
    interpretation: {
      U: 'Thermal Free Energy Reservoir U(t)',
      minus_dU_dt: 'Heat Discharge / Flux Rate (-dU/dt)',
      Phi: 'Thermal Lag & Boundary Memory Kernel Φ(t)',
      Lambda: 'Integrated Entropy Generation Λ',
      Kc: 'Boundary Thermal Conductance Kc',
    },
  },
  {
    id: 'synaptic_stdp',
    name: 'Synaptic Plasticity (STDP)',
    category: 'Neuroscience',
    description: 'Spike-timing-dependent synaptic weight adaptation where membrane potential drop triggers memory-dependent learning.',
    unitLambda: 'Δw (Synaptic Weight Shift)',
    unitPotential: 'mV (Membrane Potential Energy)',
    defaultParams: {
      Kc: 0.08,
      timeSpan: 8,
      kernelType: 'exponential',
      kernelParams: { beta: 1.2, alpha: 1, sigma: 1, mu: 3, windowWidth: 2, frequency: 1 },
      potentialType: 'multi_shock',
      potentialParams: { U0: 60, U_inf: 0, k: 1.5, shockTime: 2.5, shockSteepness: 8.0, frequency: 3, damping: 0.4 },
    },
    interpretation: {
      U: 'Membrane Action Potential U(t)',
      minus_dU_dt: 'Repolarization Voltage Drop Rate (-dU/dt)',
      Phi: 'STDP Synaptic Memory Window Φ(t)',
      Lambda: 'Total Synaptic Modification Index Λ',
      Kc: 'Learning Rate / Plasticity Coefficient Kc',
    },
  },
  {
    id: 'financial_loss',
    name: 'Capital Drawdown & Risk Loss',
    category: 'Financial Engineering',
    description: 'Quantifies cumulative drawdown risk as asset reserves drop under time-discounted market memory.',
    unitLambda: '$ Risk Exposure Index',
    unitPotential: '$ Thousands (Asset Reserve U)',
    defaultParams: {
      Kc: 1.0,
      timeSpan: 20,
      kernelType: 'exponential',
      kernelParams: { beta: 0.15, alpha: 1, sigma: 2, mu: 5, windowWidth: 5, frequency: 1 },
      potentialType: 'exponential_decay',
      potentialParams: { U0: 500, U_inf: 100, k: 0.25, shockTime: 5, shockSteepness: 2, frequency: 1, damping: 0.1 },
    },
    interpretation: {
      U: 'Portfolio Capital Reserve U(t)',
      minus_dU_dt: 'Capital Depletion / Outflow Rate (-dU/dt)',
      Phi: 'Time Discounting & Memory Decay Kernel Φ(t)',
      Lambda: 'Discounted Risk Exposure Metric Λ',
      Kc: 'Market Sensitivity Multiplier Kc',
    },
  },
  {
    id: 'battery_fade',
    name: 'Battery Electrochemistry & SEI Layer Fade',
    category: 'Energy & Storage',
    description: 'Models lithium-ion cell chemical potential drops and solid electrolyte interphase (SEI) capacity degradation with diffusion memory.',
    unitLambda: 'Ah (Irreversible Capacity Loss)',
    unitPotential: 'Wh / Cell Potential U(t)',
    defaultParams: {
      Kc: 0.85,
      timeSpan: 16,
      kernelType: 'power_law',
      kernelParams: { beta: 0.35, alpha: 0.6, sigma: 1.5, mu: 4, windowWidth: 4, frequency: 1 },
      potentialType: 'exponential_decay',
      potentialParams: { U0: 120, U_inf: 15, k: 0.35, shockTime: 4, shockSteepness: 3, frequency: 1, damping: 0.2 },
    },
    interpretation: {
      U: 'Electrochemical State of Charge Potential U(t)',
      minus_dU_dt: 'Cell Discharge & Energy Discharge Rate (-dU/dt)',
      Phi: 'SEI Growth & Diffusional Memory Kernel Φ(t)',
      Lambda: 'Accumulated Capacity Loss / SEI Thickness Λ',
      Kc: 'Electrolyte Degradation Constant Kc',
    },
  },
  {
    id: 'pharmacokinetics',
    name: 'Pharmacokinetics & Drug Receptor Exposure',
    category: 'Biomedical Engineering',
    description: 'Computes systemic receptor binding impact following bolus dosage concentration drops with metabolic clearance memory.',
    unitLambda: 'mg·h/L (Receptor Exposure AUC)',
    unitPotential: 'mg/L (Plasma Drug Concentration U)',
    defaultParams: {
      Kc: 1.5,
      timeSpan: 12,
      kernelType: 'damped_oscillator',
      kernelParams: { beta: 0.45, alpha: 1, sigma: 1, mu: 3, windowWidth: 3, frequency: 1.8 },
      potentialType: 'step_release',
      potentialParams: { U0: 200, U_inf: 5, k: 0.6, shockTime: 2.5, shockSteepness: 6.0, frequency: 1, damping: 0.3 },
    },
    interpretation: {
      U: 'Plasma Drug Concentration U(t)',
      minus_dU_dt: 'Metabolic Elimination & Clearance Rate (-dU/dt)',
      Phi: 'Receptor Binding & Elimination Lag Kernel Φ(t)',
      Lambda: 'Integrated Biological Exposure Metric Λ',
      Kc: 'Receptor Sensitivity Index Kc',
    },
  },
  {
    id: 'hydrology_runoff',
    name: 'Watershed Flooding & Dam Retention Outflow',
    category: 'Environmental Engineering',
    description: 'Simulates river basin hydro-potential drops during storm events with soil saturation memory and channel lag.',
    unitLambda: 'm³ (Accumulated Runoff Volume)',
    unitPotential: 'm³ (Hydro Reservoir Potential U)',
    defaultParams: {
      Kc: 2.0,
      timeSpan: 18,
      kernelType: 'sliding_window',
      kernelParams: { beta: 0.3, alpha: 1, sigma: 2, mu: 6, windowWidth: 4.5, frequency: 1 },
      potentialType: 'multi_shock',
      potentialParams: { U0: 300, U_inf: 40, k: 0.5, shockTime: 4.0, shockSteepness: 4.0, frequency: 1.5, damping: 0.3 },
    },
    interpretation: {
      U: 'Upstream Basin Hydro Potential U(t)',
      minus_dU_dt: 'Storm Discharge / Flow Release Rate (-dU/dt)',
      Phi: 'Soil Infiltration & Channel Lag Kernel Φ(t)',
      Lambda: 'Downstream Accumulated Flood Volume Λ',
      Kc: 'Runoff Coefficient / Basin Scale Kc',
    },
  },
  {
    id: 'magnet_quench',
    name: 'Superconducting Magnet Quench Dissipation',
    category: 'Applied Physics',
    description: 'Tracks thermal-magnetic energy loss when superconducting coils lose superconductivity, inducing eddy-current decay memory.',
    unitLambda: 'MJ (Joule Heating Energy)',
    unitPotential: 'MJ (Stored Magnetic Field Energy U)',
    defaultParams: {
      Kc: 0.95,
      timeSpan: 10,
      kernelType: 'gaussian',
      kernelParams: { beta: 0.5, alpha: 1, sigma: 1.2, mu: 3.5, windowWidth: 3, frequency: 1 },
      potentialType: 'step_release',
      potentialParams: { U0: 250, U_inf: 0, k: 1.2, shockTime: 3.0, shockSteepness: 10.0, frequency: 1, damping: 0.5 },
    },
    interpretation: {
      U: 'Stored Magnetic Field Energy U(t)',
      minus_dU_dt: 'Quench Energy Collapse Rate (-dU/dt)',
      Phi: 'Eddy Current & Thermal Diffusivity Kernel Φ(t)',
      Lambda: 'Total Resistive Heat Dissipation Λ',
      Kc: 'Coil Resistance Scaling Factor Kc',
    },
  },
  {
    id: 'ai_cluster_thermal',
    name: 'AI Data Center GPU Thermal Throttling & Power Shock',
    category: 'Computer Engineering',
    description: 'Simulates GPU cluster thermal potential drops and power supply voltage sag under intensive AI inference/training bursts.',
    unitLambda: 'kWh (Thermal Loss & Throttling Metric)',
    unitPotential: 'kW (Peak GPU Power Capacity U)',
    defaultParams: {
      Kc: 1.15,
      timeSpan: 14,
      kernelType: 'exponential',
      kernelParams: { beta: 0.6, alpha: 1, sigma: 1.5, mu: 4, windowWidth: 3, frequency: 1 },
      potentialType: 'multi_shock',
      potentialParams: { U0: 450, U_inf: 50, k: 0.7, shockTime: 3.5, shockSteepness: 5.0, frequency: 2, damping: 0.3 },
    },
    interpretation: {
      U: 'Cluster Power & Thermal Headroom U(t)',
      minus_dU_dt: 'Power Draw / Voltage Sag Rate (-dU/dt)',
      Phi: 'Cooling Radiator & Heat Pipe Thermal Lag Kernel Φ(t)',
      Lambda: 'Accumulated Cluster Throttling & Inefficiency Λ',
      Kc: 'Silicon Thermal Coupling Index Kc',
    },
  },
  {
    id: 'soc_fatigue',
    name: 'SOC Incident Alert Flooding & Analyst Fatigue',
    category: 'Operations & Cybersecurity',
    description: 'Models Security Operations Center cognitive capacity depletion during zero-day malware floods with alert lag memory.',
    unitLambda: 'Alert Fatigue & Burnout Index',
    unitPotential: 'Incidents / hr (Analyst Processing Capacity U)',
    defaultParams: {
      Kc: 1.8,
      timeSpan: 16,
      kernelType: 'sliding_window',
      kernelParams: { beta: 0.25, alpha: 1, sigma: 2, mu: 5, windowWidth: 4, frequency: 1 },
      potentialType: 'step_release',
      potentialParams: { U0: 180, U_inf: 20, k: 0.4, shockTime: 4.0, shockSteepness: 6.0, frequency: 1, damping: 0.2 },
    },
    interpretation: {
      U: 'Analyst Cognitive Processing Reserve U(t)',
      minus_dU_dt: 'Alert Triage Collapse / Inflow Pressure (-dU/dt)',
      Phi: 'Task Context Switching & Cognitive Fatigue Memory Φ(t)',
      Lambda: 'Cumulative Security Operational Risk & Burnout Λ',
      Kc: 'Operational Strain Scaling Kc',
    },
  },
  {
    id: 'quantum_decoherence',
    name: 'Superconducting Qubit Phase Coherence & Noise Dissipation',
    category: 'Quantum Computing',
    description: 'Models quantum phase coherence potential decay in transmon qubits under non-Markovian environmental flux noise memory.',
    unitLambda: 'Decoherence Phase Error Index',
    unitPotential: 'μs (Phase Coherence Energy U)',
    defaultParams: {
      Kc: 2.2,
      timeSpan: 10,
      kernelType: 'damped_oscillator',
      kernelParams: { beta: 0.8, alpha: 1, sigma: 1, mu: 3, windowWidth: 2, frequency: 2.5 },
      potentialType: 'exponential_decay',
      potentialParams: { U0: 100, U_inf: 5, k: 0.9, shockTime: 2.0, shockSteepness: 5.0, frequency: 2, damping: 0.4 },
    },
    interpretation: {
      U: 'Qubit Coherence Potential U(t)',
      minus_dU_dt: 'Phase Dephasing & Relaxation Rate (-dU/dt)',
      Phi: 'Non-Markovian Noise Memory Kernel Φ(t)',
      Lambda: 'Accumulated Quantum Phase Entropy Λ',
      Kc: 'Substrate Noise Coupling Constant Kc',
    },
  },
  {
    id: 'macroeconomics_shock',
    name: 'Central Bank Liquidity Drain & Inflation Memory',
    category: 'Macroeconomics',
    description: 'Tracks inflationary pressure accumulation as central bank balance sheet liquidity drops during quantitative tightening.',
    unitLambda: 'Cumulative Inflationary Pressure Λ',
    unitPotential: '$ Trillions (Interbank Liquidity Reserve U)',
    defaultParams: {
      Kc: 1.4,
      timeSpan: 24,
      kernelType: 'power_law',
      kernelParams: { beta: 0.1, alpha: 0.5, sigma: 2, mu: 6, windowWidth: 5, frequency: 1 },
      potentialType: 'step_release',
      potentialParams: { U0: 4.5, U_inf: 1.2, k: 0.15, shockTime: 6.0, shockSteepness: 2.0, frequency: 1, damping: 0.1 },
    },
    interpretation: {
      U: 'Interbank Liquidity Reserve U(t)',
      minus_dU_dt: 'Liquidity Withdrawal Rate (-dU/dt)',
      Phi: 'Adaptive Inflation Expectation Memory Φ(t)',
      Lambda: 'Integrated Macroeconomic Stress Metric Λ',
      Kc: 'Velocity of Money Scaling Kc',
    },
  },
  {
    id: 'epidemiology_immunity',
    name: 'Viral Pathogen Load & Immunological Memory Response',
    category: 'Epidemiology & Immunology',
    description: 'Simulates antibody affinity maturation as viral pathogen potential collapses, leaving immune memory traces.',
    unitLambda: 'Immune Neutralization Index',
    unitPotential: 'Viral Copies / mL (Pathogen Load U)',
    defaultParams: {
      Kc: 0.75,
      timeSpan: 14,
      kernelType: 'exponential',
      kernelParams: { beta: 0.3, alpha: 1, sigma: 1.5, mu: 4, windowWidth: 3, frequency: 1 },
      potentialType: 'exponential_decay',
      potentialParams: { U0: 1000, U_inf: 10, k: 0.6, shockTime: 3.0, shockSteepness: 4.0, frequency: 1, damping: 0.2 },
    },
    interpretation: {
      U: 'Pathogen Antigen Reservoir U(t)',
      minus_dU_dt: 'Immune Clearance & Phagocytosis Rate (-dU/dt)',
      Phi: 'Memory T-Cell & Plasma Cell Recall Kernel Φ(t)',
      Lambda: 'Total Immunological Protection Memory Λ',
      Kc: 'Antigenic Reactivity Index Kc',
    },
  },
  {
    id: 'grid_blackout',
    name: 'High-Voltage Power Grid Line Tripping & Cascade',
    category: 'Power Grid Engineering',
    description: 'Quantifies cascading outage risk during sudden transmission potential drops with thermal line sag memory.',
    unitLambda: 'MW-hr (Grid Instability & Load Shedding Risk)',
    unitPotential: 'GW (Grid Spinning Reserve Potential U)',
    defaultParams: {
      Kc: 2.5,
      timeSpan: 12,
      kernelType: 'gaussian',
      kernelParams: { beta: 0.4, alpha: 1, sigma: 1.0, mu: 3.0, windowWidth: 2, frequency: 1 },
      potentialType: 'multi_shock',
      potentialParams: { U0: 50, U_inf: 10, k: 1.1, shockTime: 2.5, shockSteepness: 8.0, frequency: 2, damping: 0.3 },
    },
    interpretation: {
      U: 'Grid Voltage & Spinning Reserve U(t)',
      minus_dU_dt: 'Substation Load Loss Rate (-dU/dt)',
      Phi: 'Transformer Thermal Sag & Inertia Memory Φ(t)',
      Lambda: 'Integrated Blackout Cascade Energy Λ',
      Kc: 'Grid Interconnection Impedance Kc',
    },
  },
];
